# Generated by Django 4.1.7 on 2023-04-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image1', models.ImageField(blank=True, upload_to='product')),
                ('image2', models.ImageField(blank=True, upload_to='product')),
                ('image3', models.ImageField(blank=True, upload_to='product')),
                ('image4', models.ImageField(blank=True, upload_to='product')),
                ('image5', models.ImageField(blank=True, upload_to='product')),
                ('image6', models.ImageField(blank=True, upload_to='product')),
                ('image7', models.ImageField(blank=True, upload_to='product')),
                ('image8', models.ImageField(blank=True, upload_to='product')),
                ('image9', models.ImageField(blank=True, upload_to='product')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
